# Assignment 1

# Task: Implemantation of any 50 numpy methods or attribute codes in jupyter notebook

# Student Name : Qausain Manzoor
# Roll No: 82252
# Batch : 6
# Location: Sialkot
# Teacher: Sir Qasim

In [1]:
import numpy as np

# 1- Arithmetic with Numpy Arrays

In [ ]:
# Arithmetic with Numpy Arrays

In [2]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

In [3]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

# 2- Basic Indexing & Slicing

In [ ]:
# Basic Indexing & Slicing

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[5]

5

In [8]:
arr[5:8]

array([5, 6, 7])

# 3- Reshape

In [9]:
a= np.arange(1,13)

In [10]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# 4- Numpy Tile & Repeat

In [12]:
a = np.array([1,5,7,8])

In [13]:
a

array([1, 5, 7, 8])

In [14]:
np.repeat(a,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [15]:
np.tile(a,3)

array([1, 5, 7, 8, 1, 5, 7, 8, 1, 5, 7, 8])

# 5- How to create a 1D array?

In [16]:
arr = np.array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

# 6- How to create a boolean array?

In [18]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 7- How to extract items that satisfy a given condition from 1D array?

In [ ]:
#Extract all odd numbers from arr

In [19]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

# 8- How to replace items that satisfy a condition with another value in numpy array?

In [ ]:
#Replace all odd numbers in arr with -1

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 9-How to replace items that satisfy a condition without affecting the original array?

In [ ]:
#Replace all odd numbers in arr with -1 without changing arr

In [23]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# 10-How to reshape an array?

In [ ]:
#Convert a 1D array to a 2D array with 2 rows

In [25]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 11-How to stack two arrays vertically?

In [ ]:
#Stack arrays a and b vertically

In [26]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [27]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 12-How to stack two arrays horizontally?

In [ ]:
#Stack the arrays a and b horizontally.

In [28]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 13-How to generate custom sequences in numpy without hardcoding?

In [ ]:
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [29]:
a = np.array([1,2,3])

In [30]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 14-How to get the common items between two python numpy arrays?

In [ ]:
#Get the common items between a and b

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [32]:
np.intersect1d(a,b)

array([2, 4])

# 15-How to remove from one array those items that exist in another?

In [ ]:
#From array a remove all items present in array b

In [33]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [34]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 16-How to get the positions where elements of two arrays match?

In [ ]:
#Get the positions where elements of a and b match

In [35]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [36]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

# 17-How to extract all numbers between a given range from a numpy array?

In [ ]:
#Get all items between 5 and 10 from a.

In [37]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [38]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

# 18-How to make a python function that handles scalars to work on numpy arrays?

In [ ]:
#Convert the function maxx that works on two scalars, to work on two arrays.

In [39]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

# 19-How to swap two columns in a 2d numpy array?

In [ ]:
#Swap rows 1 and 2 in the array arr:

In [40]:
arr = np.arange(9).reshape(3,3)

In [41]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 20-How to reverse the rows of a 2D array?

In [ ]:
#Reverse the rows of a 2D array arr

In [42]:
arr = np.arange(9).reshape(3,3)

In [43]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 21-How to create a 2D array containing random floats between 5 and 10?

In [ ]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [44]:
arr = np.arange(9).reshape(3,3)

In [45]:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[8.24588061 5.09419537 9.88481586]
 [7.22295192 8.89562418 8.71697214]
 [8.58477292 9.36715217 5.93382905]
 [9.6714685  6.31787646 9.79421938]
 [7.80803784 9.82733064 6.96332228]]


# 22-How to print only 3 decimal places in python numpy array?

In [ ]:
#Print or show only 3 decimal places of the numpy array rand_arr

In [46]:
rand_arr = np.random.random((5,3))

In [47]:
rand_arr = np.random.random([5,3])

In [48]:
np.set_printoptions(precision=3)
rand_arr[:4]

array([[9.580e-01, 9.782e-01, 8.046e-01],
       [2.277e-01, 7.602e-01, 7.991e-04],
       [5.570e-01, 9.379e-01, 9.806e-01],
       [8.971e-01, 8.936e-01, 7.223e-01]])

# 23-How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [ ]:
#Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [49]:
np.set_printoptions(suppress=False)

In [50]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [51]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

# 24-How to limit the number of items printed in output of numpy array?

In [ ]:
#Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [52]:
a = np.arange(15)

In [53]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

# 25-How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [ ]:
#Import the iris dataset keeping the text intact.

In [54]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [55]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

# 26-How to replace all values greater than a given value to a given cutoff?

In [ ]:
#From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [56]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [57]:
np.clip(a, a_min=10, a_max=30)

array([27.63, 14.64, 21.8 , ..., 10.  , 30.  , 14.43])

In [58]:
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.63 14.64 21.8  ... 10.   30.   14.43]


# 27-How to get the positions of top n values from a numpy array?

In [ ]:
#Get the positions of top 5 maximum values in a given array a

In [59]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [60]:
print(a.argsort())

[ 4 13  5 ...  3 10 15]


In [61]:
np.sort(a)[-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

# 28-How to Reshape an array?

In [ ]:
#Reshaping 1d array in 2d or 3d array

In [71]:
a= np.arange(1,13)

In [72]:
a

array([ 1,  2,  3, ..., 10, 11, 12])

In [73]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [74]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 29-How to replace all values greater than a given value to a given cutoff?

In [ ]:
# From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [64]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [65]:
np.clip(a, a_min=10, a_max=30)

array([27.63, 14.64, 21.8 , ..., 10.  , 30.  , 14.43])

# 30-How to get the positions of top n values from a numpy array?

In [ ]:
#Get the positions of top 5 maximum values in a given array a

In [66]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [67]:
print(a.argsort())

[ 4 13  5 ...  3 10 15]


In [68]:
a[a.argsort()][-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

# 31-How to compute the row wise counts of all possible values in an array?

In [ ]:
#Compute the counts of unique values row-wise

In [69]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4, ...,  3,  6,  3],
       [ 3,  3,  2, ..., 10,  7,  3],
       [ 5,  2,  6, ...,  8,  2,  2],
       [ 8,  8,  1, ...,  3,  6,  9],
       [ 2,  1,  8, ...,  3,  6,  2],
       [ 9,  2,  6, ...,  6,  1, 10]])

In [70]:
def counts_of_all_values_rowwise(arr2d):
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3 ...  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

# 32-How to convert an array of arrays into a flat 1d array?

In [ ]:
#Convert array_of_arrays into a flat linear 1d array

In [75]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)


array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]


In [76]:
arr_2d = np.array([a for arr in array_of_arrays for a in arr])
print(arr_2d)

[0 1 2 ... 7 8 9]


# 33-How to generate one-hot encodings for an array in numpy?

In [ ]:
# Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [77]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

In [78]:
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

# 34-How to rank items in an array using numpy?

In [ ]:
#Create the ranks for the given numeric array a.

In [79]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)

Array:  [ 9  4 15 ...  8  9  0]


In [80]:
print(a.argsort().argsort())
print('Array: ', a)

[4 2 6 ... 3 5 1]
Array:  [ 9  4 15 ...  8  9  0]


# 35-How to rank items in a multidimensional array using numpy?

In [ ]:
#Create a rank array of the same shape as a given numeric array a.

In [81]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [82]:
print(a.ravel().argsort().argsort().reshape(a.shape))

[[4 2 6 0 8]
 [7 9 3 5 1]]


# 36-How to find the maximum value in each row of a numpy array 2d?

In [ ]:
#Compute the maximum for each row in the given array.

In [83]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [84]:
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

# 37-How to compute the min-by-max for each row for a numpy array 2d?

In [ ]:
#Compute the min-by-max for each row for given 2d numpy array

In [85]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [86]:
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.44, 0.12, 0.5 , 1.  , 0.11])

# 38-How to find the duplicate records in a numpy array?

In [ ]:
#Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. 
#First time occurrences should be False.

In [87]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, ..., 2, 2, 2])

In [88]:
out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index=True)[1]
out[unique_positions] = False

print(out)

[False  True False ...  True  True  True]


# 39-How to convert a PIL image to numpy array?

In [ ]:
#Import the image from the following URL and convert it to a numpy array.

#URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [89]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

In [90]:
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([750,750])

# Convert to numpy array
arr = np.asarray(I)

In [91]:
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

# 40-How to drop all missing values from a numpy array?

In [ ]:
#Drop all nan values from a 1D numpy array

In [92]:
np.array([1,2,3,np.nan,5,6,7,np.nan])

array([ 1.,  2.,  3., ...,  6.,  7., nan])

In [93]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

# 41-How to compute the euclidean distance between two arrays?

In [ ]:
#Compute the euclidean distance between two arrays a and b.

In [94]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [95]:
dist = np.linalg.norm(a-b)
dist

6.708203932499369

# 42-How to find all the local maxima (or peaks) in a 1d array?

In [ ]:
#Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

In [96]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

In [97]:
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

# 43-How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?

In [ ]:
#Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

In [98]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [99]:
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


# 44-How to find the index of n'th repetition of an item in an array?

In [ ]:
# Find the index of 5th repetition of number 1 in x.

In [100]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

In [101]:
[i for i, v in enumerate(x) if v == 1][n-1]

8

# 45-How to convert numpy's datetime64 object to datetime's datetime object?

In [ ]:
#Convert numpy's datetime64 object to datetime's datetime object.

In [102]:
dt64 = np.datetime64('2018-02-25 22:10:10')

In [103]:
from datetime import datetime
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

# 46-How to create a numpy array sequence given only the starting point, length and the step?

In [ ]:
#Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [104]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, ..., 26, 29, 32])

# 47-How to fill in missing dates in an irregular series of numpy dates?

In [ ]:
#Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

In [105]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

['2018-02-01' '2018-02-03' '2018-02-05' ... '2018-02-19' '2018-02-21'
 '2018-02-23']


In [106]:
filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)

# add the last day
output = np.hstack([filled_in, dates[-1]])
output

# For loop version -------
out = []
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))

filled_in = np.array(out).reshape(-1)

# add the last day
output = np.hstack([filled_in, dates[-1]])
output

array(['2018-02-01', '2018-02-02', '2018-02-03', ..., '2018-02-21',
       '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

# 48-How to calculate mean?

In [107]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [108]:
a

array([ 1,  2,  3, ...,  8,  9, 10])

In [109]:
a.mean()

5.5

# 49- How to calculate cumsum?

In [110]:
a.cumsum()

array([ 1,  3,  6, ..., 36, 45, 55], dtype=int32)

# 50- How to compute transpose of a Matrix?

In [111]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])